# Generated by Django 4.2.4 on 2023-08-26 00:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('completed', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
